# AUTO-GENERATED FILE — DO NOT EDIT MANUALLY.
# Regenerate with: make gen
#
"""Tests package."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import TYPE_CHECKING as _TYPE_CHECKING

from flext_core.lazy import install_lazy_exports, merge_lazy_imports

if _TYPE_CHECKING:
    from flext_core import FlextTypes
    from flext_tests import d, e, h, r, s, x

    from tests import (
        conftest,
        constants,
        helpers,
        integration,
        models,
        protocols,
        typings,
        unit,
        utilities,
    )
    from tests.conftest import (
        CliRunner,
        MockCliResult,
        MockCliRunner,
        MockMeltanoService,
        MockSingerTap,
        MockSingerTarget,
        job_run_config,
        meltano_cli_runner,
        meltano_invoke_args,
        meltano_project,
        meltano_service,
        meltano_yml_config,
        mock_meltano_service,
        mock_singer_tap,
        mock_singer_target,
        pipeline_execution_config,
        postgres_service,
        pytest_configure,
        redis_service,
        sample_csv_data,
        sample_schedule_config,
        set_test_environment,
        singer_records,
        singer_schema,
        singer_state,
        tap_csv_config,
        target_csv_config,
        test_environment_config,
        test_meltano_project_dir,
    )
    from tests.constants import (
        FlextMeltanoTestConstants,
        FlextMeltanoTestConstants as c,
    )
    from tests.helpers import (
        ContainerManager,
        Tk,
        docker_manager,
        docker_services,
        docker_test_manager,
    )
    from tests.integration import (
        TestDockerIntegration,
        psycopg2,
        redis,
        test_docker_integration,
    )
    from tests.models import FlextMeltanoTestModels, FlextMeltanoTestModels as m
    from tests.protocols import (
        FlextMeltanoTestProtocols,
        FlextMeltanoTestProtocols as p,
    )
    from tests.typings import FlextMeltanoTestTypes, FlextMeltanoTestTypes as t
    from tests.unit import (
        LogLevel,
        Testc,
        TestCliModelConverterWithDbtRunParams,
        TestCliModelConverterWithPipelineRunParams,
        TestCliModelConverterWithTapRunParams,
        TestCliModelConverterWithTargetRunParams,
        TestDbtProjectModelEnhanced,
        TestDbtService,
        TestFlextMeltanoAbstractionsComplete,
        TestFlextMeltanoCatalogOperations,
        TestFlextMeltanoErrorHandling,
        TestFlextMeltanoExecuteMethod,
        TestFlextMeltanoExecutionResult,
        TestFlextMeltanoExecutorComplete,
        TestFlextMeltanoFileManagersComprehensive,
        TestFlextMeltanoInitialization,
        TestFlextMeltanoIntegration,
        TestFlextMeltanoLibraryRunner,
        TestFlextMeltanoPerformance,
        TestFlextMeltanoPipelineOperations,
        TestFlextMeltanoPluginOperations,
        TestFlextMeltanoPluginProtocols,
        TestFlextMeltanoProjectOperations,
        TestFlextMeltanoServiceInitialization,
        TestFlextMeltanoSettings,
        TestFlextMeltanoSettingsConstants,
        TestFlextMeltanoSettingsEdgeCases,
        TestFlextMeltanoSettingsEnums,
        TestFlextMeltanoSettingsIntegration,
        TestFlextMeltanoSingerCliTranslatorDbtRun,
        TestFlextMeltanoSingerCliTranslatorExecuteCommand,
        TestFlextMeltanoSingerCliTranslatorPipelineRun,
        TestFlextMeltanoSingerCliTranslatorTapRun,
        TestFlextMeltanoSingerCliTranslatorTargetRun,
        TestFlextMeltanoSuccessPaths,
        TestFlextMeltanoTargetAbstractionsComplete,
        TestFlextMeltanoTypes,
        TestFlextMeltanoUtilitiesEnhanced,
        TestFlextMeltanoValidatorsComprehensive,
        TestFlextSingerTypes,
        TestMeltanoProjectModelEnhanced,
        TestModelIntegration,
        TestPluginModelEnhanced,
        TestProjectAdapterIntegration,
        TestServiceArchitecture,
        TestServiceErrorHandling,
        TestServiceFactoryMethods,
        TestServiceGenericMethods,
        TestServiceIntegration,
        TestStreamInfoEnhanced,
        TestTapConfigEnhanced,
        TestTapService,
        TestTargetConfigEnhanced,
        TestTargetService,
        create_pipeline,
        delete_pipeline,
        execute_pipeline,
        get_pipeline_status,
        list_pipelines,
        logger,
        pipeline_cli_managers_tests,
        pytestmark,
        test_api,
        test_cli_integration,
        test_config,
        test_constants,
        test_create_pipeline_creates_directory_and_configuration,
        test_create_pipeline_fails_without_configuration,
        test_delete_pipeline_removes_configuration_directory,
        test_execute_pipeline_fails_when_pipeline_execution_is_not_configured,
        test_execute_pipeline_runs_real_subprocess_contract,
        test_execution_result,
        test_executors,
        test_file_managers,
        test_get_pipeline_status_checks_process_state,
        test_library_runner,
        test_models,
        test_pipeline_manager_lifecycle_commands_delegate_to_real_operations,
        test_plugin_protocols,
        test_services,
        test_singer_cli_translator,
        test_singer_types,
        test_tap_abstractions,
        test_target_abstractions,
        test_typings,
        test_utilities,
        test_validators,
    )
    from tests.utilities import (
        FlextMeltanoTestUtilities,
        FlextMeltanoTestUtilities as u,
    )

_LAZY_IMPORTS: Mapping[str, str | Sequence[str]] = merge_lazy_imports(
    (
        "tests.helpers",
        "tests.integration",
        "tests.unit",
    ),
    {
        "CliRunner": "tests.conftest",
        "FlextMeltanoTestConstants": "tests.constants",
        "FlextMeltanoTestModels": "tests.models",
        "FlextMeltanoTestProtocols": "tests.protocols",
        "FlextMeltanoTestTypes": "tests.typings",
        "FlextMeltanoTestUtilities": "tests.utilities",
        "MockCliResult": "tests.conftest",
        "MockCliRunner": "tests.conftest",
        "MockMeltanoService": "tests.conftest",
        "MockSingerTap": "tests.conftest",
        "MockSingerTarget": "tests.conftest",
        "c": ("tests.constants", "FlextMeltanoTestConstants"),
        "conftest": "tests.conftest",
        "constants": "tests.constants",
        "d": "flext_tests",
        "e": "flext_tests",
        "h": "flext_tests",
        "helpers": "tests.helpers",
        "integration": "tests.integration",
        "job_run_config": "tests.conftest",
        "m": ("tests.models", "FlextMeltanoTestModels"),
        "meltano_cli_runner": "tests.conftest",
        "meltano_invoke_args": "tests.conftest",
        "meltano_project": "tests.conftest",
        "meltano_service": "tests.conftest",
        "meltano_yml_config": "tests.conftest",
        "mock_meltano_service": "tests.conftest",
        "mock_singer_tap": "tests.conftest",
        "mock_singer_target": "tests.conftest",
        "models": "tests.models",
        "p": ("tests.protocols", "FlextMeltanoTestProtocols"),
        "pipeline_execution_config": "tests.conftest",
        "postgres_service": "tests.conftest",
        "protocols": "tests.protocols",
        "pytest_configure": "tests.conftest",
        "r": "flext_tests",
        "redis_service": "tests.conftest",
        "s": "flext_tests",
        "sample_csv_data": "tests.conftest",
        "sample_schedule_config": "tests.conftest",
        "set_test_environment": "tests.conftest",
        "singer_records": "tests.conftest",
        "singer_schema": "tests.conftest",
        "singer_state": "tests.conftest",
        "t": ("tests.typings", "FlextMeltanoTestTypes"),
        "tap_csv_config": "tests.conftest",
        "target_csv_config": "tests.conftest",
        "test_environment_config": "tests.conftest",
        "test_meltano_project_dir": "tests.conftest",
        "typings": "tests.typings",
        "u": ("tests.utilities", "FlextMeltanoTestUtilities"),
        "unit": "tests.unit",
        "utilities": "tests.utilities",
        "x": "flext_tests",
    },
)


install_lazy_exports(__name__, globals(), _LAZY_IMPORTS)
