# AUTO-GENERATED FILE — DO NOT EDIT MANUALLY.
# Regenerate with: make gen
#
"""Tests package."""

from __future__ import annotations

import typing as _t

from flext_core.lazy import install_lazy_exports, merge_lazy_imports

if _t.TYPE_CHECKING:
    import tests.conftest as _tests_conftest

    conftest = _tests_conftest
    import tests.constants as _tests_constants
    from tests.conftest import (
        CliRunner,
        MockCliResult,
        MockCliRunner,
        MockMeltanoService,
        MockSingerTap,
        MockSingerTarget,
        job_run_config,
        meltano_cli_runner,
        meltano_invoke_args,
        meltano_project,
        meltano_service,
        meltano_yml_config,
        mock_meltano_service,
        mock_singer_tap,
        mock_singer_target,
        pipeline_execution_config,
        postgres_service,
        pytest_configure,
        pytest_plugins,
        redis_service,
        sample_csv_data,
        sample_schedule_config,
        set_test_environment,
        singer_records,
        singer_schema,
        singer_state,
        tap_csv_config,
        target_csv_config,
        test_environment_config,
        test_meltano_project_dir,
    )

    constants = _tests_constants
    import tests.helpers as _tests_helpers
    from tests.constants import (
        FlextMeltanoTestConstants,
        FlextMeltanoTestConstants as c,
    )

    helpers = _tests_helpers
    import tests.integration as _tests_integration
    from tests.helpers import (
        ContainerManager,
        Tk,
        docker_manager,
        docker_services,
        docker_test_manager,
    )

    integration = _tests_integration
    import tests.models as _tests_models
    from tests.integration import (
        TestDockerIntegration,
        psycopg2,
        redis,
        test_docker_integration,
    )

    models = _tests_models
    import tests.protocols as _tests_protocols
    from tests.models import FlextMeltanoTestModels, FlextMeltanoTestModels as m

    protocols = _tests_protocols
    import tests.typings as _tests_typings
    from tests.protocols import (
        FlextMeltanoTestProtocols,
        FlextMeltanoTestProtocols as p,
    )

    typings = _tests_typings
    import tests.unit as _tests_unit
    from tests.typings import FlextMeltanoTestTypes, FlextMeltanoTestTypes as t

    unit = _tests_unit
    import tests.utilities as _tests_utilities
    from tests.unit import (
        Testc,
        TestCliModelConversionWithDbtRunParams,
        TestCliModelConversionWithPipelineRunParams,
        TestCliModelConversionWithTapRunParams,
        TestCliModelConversionWithTargetRunParams,
        TestDbtProjectModelEnhanced,
        TestDbtService,
        TestFlextMeltanoAbstractionsComplete,
        TestFlextMeltanoCatalogOperations,
        TestFlextMeltanoErrorHandling,
        TestFlextMeltanoExecuteMethod,
        TestFlextMeltanoExecutionResult,
        TestFlextMeltanoExecutorComplete,
        TestFlextMeltanoInitialization,
        TestFlextMeltanoIntegration,
        TestFlextMeltanoLibraryRunner,
        TestFlextMeltanoPerformance,
        TestFlextMeltanoPipelineOperations,
        TestFlextMeltanoPluginOperations,
        TestFlextMeltanoPluginProtocols,
        TestFlextMeltanoProjectOperations,
        TestFlextMeltanoServiceInitialization,
        TestFlextMeltanoSingerCliTranslatorDbtRun,
        TestFlextMeltanoSingerCliTranslatorExecuteCommand,
        TestFlextMeltanoSingerCliTranslatorPipelineRun,
        TestFlextMeltanoSingerCliTranslatorTapRun,
        TestFlextMeltanoSingerCliTranslatorTargetRun,
        TestFlextMeltanoSuccessPaths,
        TestFlextMeltanoTargetAbstractionsComplete,
        TestFlextMeltanoTypes,
        TestFlextMeltanoValidatorsComprehensive,
        TestFlextSingerTypes,
        TestMeltanoProjectModelEnhanced,
        TestModelIntegration,
        TestPluginModelEnhanced,
        TestProjectAdapterIntegration,
        TestServiceArchitecture,
        TestServiceErrorHandling,
        TestServiceFactoryMethods,
        TestServiceGenericMethods,
        TestServiceIntegration,
        TestStreamInfoEnhanced,
        TestTapConfigEnhanced,
        TestTapService,
        TestTargetConfigEnhanced,
        TestTargetService,
        create_pipeline,
        delete_pipeline,
        execute_pipeline,
        get_pipeline_status,
        list_pipelines,
        logger,
        pipeline_cli_managers_tests,
        pytestmark,
        test_adapter_delegates_sync,
        test_adapter_exposes_config_and_streams,
        test_adapter_normalizes_successful_cli_exit_code,
        test_adapter_normalizes_system_exit,
        test_api,
        test_cli_integration,
        test_constants,
        test_create_pipeline_creates_directory_and_configuration,
        test_create_pipeline_fails_without_configuration,
        test_delete_pipeline_removes_configuration_directory,
        test_execute_pipeline_fails_when_pipeline_execution_is_not_configured,
        test_execute_pipeline_runs_real_subprocess_contract,
        test_execution_result,
        test_executors,
        test_get_pipeline_status_checks_process_state,
        test_library_runner,
        test_models,
        test_pipeline_manager_lifecycle_commands_delegate_to_real_operations,
        test_plugin_protocols,
        test_services,
        test_singer_cli_translator,
        test_singer_sdk_adapter,
        test_singer_types,
        test_tap_abstractions,
        test_target_abstractions,
        test_typings,
        test_validators,
    )

    utilities = _tests_utilities
    from flext_core.decorators import FlextDecorators as d
    from flext_core.exceptions import FlextExceptions as e
    from flext_core.handlers import FlextHandlers as h
    from flext_core.mixins import FlextMixins as x
    from flext_core.result import FlextResult as r
    from flext_core.service import FlextService as s
    from tests.utilities import (
        FlextMeltanoTestUtilities,
        FlextMeltanoTestUtilities as u,
    )
_LAZY_IMPORTS = merge_lazy_imports(
    (
        "tests.helpers",
        "tests.integration",
        "tests.unit",
    ),
    {
        "CliRunner": ("tests.conftest", "CliRunner"),
        "FlextMeltanoTestConstants": ("tests.constants", "FlextMeltanoTestConstants"),
        "FlextMeltanoTestModels": ("tests.models", "FlextMeltanoTestModels"),
        "FlextMeltanoTestProtocols": ("tests.protocols", "FlextMeltanoTestProtocols"),
        "FlextMeltanoTestTypes": ("tests.typings", "FlextMeltanoTestTypes"),
        "FlextMeltanoTestUtilities": ("tests.utilities", "FlextMeltanoTestUtilities"),
        "MockCliResult": ("tests.conftest", "MockCliResult"),
        "MockCliRunner": ("tests.conftest", "MockCliRunner"),
        "MockMeltanoService": ("tests.conftest", "MockMeltanoService"),
        "MockSingerTap": ("tests.conftest", "MockSingerTap"),
        "MockSingerTarget": ("tests.conftest", "MockSingerTarget"),
        "c": ("tests.constants", "FlextMeltanoTestConstants"),
        "conftest": "tests.conftest",
        "constants": "tests.constants",
        "d": ("flext_core.decorators", "FlextDecorators"),
        "e": ("flext_core.exceptions", "FlextExceptions"),
        "h": ("flext_core.handlers", "FlextHandlers"),
        "helpers": "tests.helpers",
        "integration": "tests.integration",
        "job_run_config": ("tests.conftest", "job_run_config"),
        "m": ("tests.models", "FlextMeltanoTestModels"),
        "meltano_cli_runner": ("tests.conftest", "meltano_cli_runner"),
        "meltano_invoke_args": ("tests.conftest", "meltano_invoke_args"),
        "meltano_project": ("tests.conftest", "meltano_project"),
        "meltano_service": ("tests.conftest", "meltano_service"),
        "meltano_yml_config": ("tests.conftest", "meltano_yml_config"),
        "mock_meltano_service": ("tests.conftest", "mock_meltano_service"),
        "mock_singer_tap": ("tests.conftest", "mock_singer_tap"),
        "mock_singer_target": ("tests.conftest", "mock_singer_target"),
        "models": "tests.models",
        "p": ("tests.protocols", "FlextMeltanoTestProtocols"),
        "pipeline_execution_config": ("tests.conftest", "pipeline_execution_config"),
        "postgres_service": ("tests.conftest", "postgres_service"),
        "protocols": "tests.protocols",
        "pytest_configure": ("tests.conftest", "pytest_configure"),
        "pytest_plugins": ("tests.conftest", "pytest_plugins"),
        "r": ("flext_core.result", "FlextResult"),
        "redis_service": ("tests.conftest", "redis_service"),
        "s": ("flext_core.service", "FlextService"),
        "sample_csv_data": ("tests.conftest", "sample_csv_data"),
        "sample_schedule_config": ("tests.conftest", "sample_schedule_config"),
        "set_test_environment": ("tests.conftest", "set_test_environment"),
        "singer_records": ("tests.conftest", "singer_records"),
        "singer_schema": ("tests.conftest", "singer_schema"),
        "singer_state": ("tests.conftest", "singer_state"),
        "t": ("tests.typings", "FlextMeltanoTestTypes"),
        "tap_csv_config": ("tests.conftest", "tap_csv_config"),
        "target_csv_config": ("tests.conftest", "target_csv_config"),
        "test_environment_config": ("tests.conftest", "test_environment_config"),
        "test_meltano_project_dir": ("tests.conftest", "test_meltano_project_dir"),
        "typings": "tests.typings",
        "u": ("tests.utilities", "FlextMeltanoTestUtilities"),
        "unit": "tests.unit",
        "utilities": "tests.utilities",
        "x": ("flext_core.mixins", "FlextMixins"),
    },
)
_ = _LAZY_IMPORTS.pop("cleanup_submodule_namespace", None)
_ = _LAZY_IMPORTS.pop("install_lazy_exports", None)
_ = _LAZY_IMPORTS.pop("lazy_getattr", None)
_ = _LAZY_IMPORTS.pop("merge_lazy_imports", None)
_ = _LAZY_IMPORTS.pop("output", None)
_ = _LAZY_IMPORTS.pop("output_reporting", None)

__all__ = [
    "CliRunner",
    "ContainerManager",
    "FlextMeltanoTestConstants",
    "FlextMeltanoTestModels",
    "FlextMeltanoTestProtocols",
    "FlextMeltanoTestTypes",
    "FlextMeltanoTestUtilities",
    "MockCliResult",
    "MockCliRunner",
    "MockMeltanoService",
    "MockSingerTap",
    "MockSingerTarget",
    "TestCliModelConversionWithDbtRunParams",
    "TestCliModelConversionWithPipelineRunParams",
    "TestCliModelConversionWithTapRunParams",
    "TestCliModelConversionWithTargetRunParams",
    "TestDbtProjectModelEnhanced",
    "TestDbtService",
    "TestDockerIntegration",
    "TestFlextMeltanoAbstractionsComplete",
    "TestFlextMeltanoCatalogOperations",
    "TestFlextMeltanoErrorHandling",
    "TestFlextMeltanoExecuteMethod",
    "TestFlextMeltanoExecutionResult",
    "TestFlextMeltanoExecutorComplete",
    "TestFlextMeltanoInitialization",
    "TestFlextMeltanoIntegration",
    "TestFlextMeltanoLibraryRunner",
    "TestFlextMeltanoPerformance",
    "TestFlextMeltanoPipelineOperations",
    "TestFlextMeltanoPluginOperations",
    "TestFlextMeltanoPluginProtocols",
    "TestFlextMeltanoProjectOperations",
    "TestFlextMeltanoServiceInitialization",
    "TestFlextMeltanoSingerCliTranslatorDbtRun",
    "TestFlextMeltanoSingerCliTranslatorExecuteCommand",
    "TestFlextMeltanoSingerCliTranslatorPipelineRun",
    "TestFlextMeltanoSingerCliTranslatorTapRun",
    "TestFlextMeltanoSingerCliTranslatorTargetRun",
    "TestFlextMeltanoSuccessPaths",
    "TestFlextMeltanoTargetAbstractionsComplete",
    "TestFlextMeltanoTypes",
    "TestFlextMeltanoValidatorsComprehensive",
    "TestFlextSingerTypes",
    "TestMeltanoProjectModelEnhanced",
    "TestModelIntegration",
    "TestPluginModelEnhanced",
    "TestProjectAdapterIntegration",
    "TestServiceArchitecture",
    "TestServiceErrorHandling",
    "TestServiceFactoryMethods",
    "TestServiceGenericMethods",
    "TestServiceIntegration",
    "TestStreamInfoEnhanced",
    "TestTapConfigEnhanced",
    "TestTapService",
    "TestTargetConfigEnhanced",
    "TestTargetService",
    "Testc",
    "Tk",
    "c",
    "conftest",
    "constants",
    "create_pipeline",
    "d",
    "delete_pipeline",
    "docker_manager",
    "docker_services",
    "docker_test_manager",
    "e",
    "execute_pipeline",
    "get_pipeline_status",
    "h",
    "helpers",
    "integration",
    "job_run_config",
    "list_pipelines",
    "logger",
    "m",
    "meltano_cli_runner",
    "meltano_invoke_args",
    "meltano_project",
    "meltano_service",
    "meltano_yml_config",
    "mock_meltano_service",
    "mock_singer_tap",
    "mock_singer_target",
    "models",
    "p",
    "pipeline_cli_managers_tests",
    "pipeline_execution_config",
    "postgres_service",
    "protocols",
    "psycopg2",
    "pytest_configure",
    "pytest_plugins",
    "pytestmark",
    "r",
    "redis",
    "redis_service",
    "s",
    "sample_csv_data",
    "sample_schedule_config",
    "set_test_environment",
    "singer_records",
    "singer_schema",
    "singer_state",
    "t",
    "tap_csv_config",
    "target_csv_config",
    "test_adapter_delegates_sync",
    "test_adapter_exposes_config_and_streams",
    "test_adapter_normalizes_successful_cli_exit_code",
    "test_adapter_normalizes_system_exit",
    "test_api",
    "test_cli_integration",
    "test_constants",
    "test_create_pipeline_creates_directory_and_configuration",
    "test_create_pipeline_fails_without_configuration",
    "test_delete_pipeline_removes_configuration_directory",
    "test_docker_integration",
    "test_environment_config",
    "test_execute_pipeline_fails_when_pipeline_execution_is_not_configured",
    "test_execute_pipeline_runs_real_subprocess_contract",
    "test_execution_result",
    "test_executors",
    "test_get_pipeline_status_checks_process_state",
    "test_library_runner",
    "test_meltano_project_dir",
    "test_models",
    "test_pipeline_manager_lifecycle_commands_delegate_to_real_operations",
    "test_plugin_protocols",
    "test_services",
    "test_singer_cli_translator",
    "test_singer_sdk_adapter",
    "test_singer_types",
    "test_tap_abstractions",
    "test_target_abstractions",
    "test_typings",
    "test_validators",
    "typings",
    "u",
    "unit",
    "utilities",
    "x",
]


install_lazy_exports(__name__, globals(), _LAZY_IMPORTS)
