
from __future__ import annotations

import pytest
from flext_meltano.exceptions import ( Copyright (c) 2025 FLEXT Team. All rights reserved. SPDX-License-Identifier: MIT """ from __future__ import annotations FlextMeltanoAuthenticationError, FlextMeltanoBaseError, FlextMeltanoConfigurationError, FlextMeltanoConnectionError, FlextMeltanoError, FlextMeltanoProcessingError, FlextMeltanoTimeoutError, FlextMeltanoValidationError, )


class TestFlextMeltanoExceptions:
    """Test flext-core generated FlextMeltano exceptions - ZERO duplication."""

    def test_base_error_functionality(self) -> None:
        """Test FlextMeltanoBaseError - generated by flext-core."""

        error = FlextMeltanoBaseError("Base error message")
        assert "Base error message" in str(error)
        assert isinstance(error, Exception)

    def test_meltano_error_functionality(self) -> None:
        """Test FlextMeltanoError - generated by flext-core."""

        error = FlextMeltanoError("Meltano operation failed")
        assert "Meltano operation failed" in str(error)
        assert isinstance(error, FlextMeltanoBaseError)

    def test_validation_error_functionality(self) -> None:
        """Test FlextMeltanoValidationError - generated by flext-core."""

        error = FlextMeltanoValidationError("Validation failed for field 'name'")
        assert "Validation failed for field 'name'" in str(error)
        assert isinstance(error, FlextMeltanoBaseError)

    def test_configuration_error_functionality(self) -> None:
        """Test FlextMeltanoConfigurationError - generated by flext-core."""

        error = FlextMeltanoConfigurationError("Invalid configuration")
        assert "Invalid configuration" in str(error)
        assert isinstance(error, FlextMeltanoBaseError)

    def test_connection_error_functionality(self) -> None:
        """Test FlextMeltanoConnectionError - generated by flext-core."""

        error = FlextMeltanoConnectionError("Database connection failed")
        assert "Database connection failed" in str(error)
        assert isinstance(error, FlextMeltanoBaseError)

    def test_authentication_error_functionality(self) -> None:
        """Test FlextMeltanoAuthenticationError - generated by flext-core."""

        error = FlextMeltanoAuthenticationError("Authentication failed")
        assert "Authentication failed" in str(error)
        assert isinstance(error, FlextMeltanoBaseError)

    def test_processing_error_functionality(self) -> None:
        """Test FlextMeltanoProcessingError - generated by flext-core."""

        error = FlextMeltanoProcessingError("Data processing failed")
        assert "Data processing failed" in str(error)
        assert isinstance(error, FlextMeltanoBaseError)

    def test_timeout_error_functionality(self) -> None:
        """Test FlextMeltanoTimeoutError - generated by flext-core."""

        error = FlextMeltanoTimeoutError("Operation timed out")
        assert "Operation timed out" in str(error)
        assert isinstance(error, FlextMeltanoBaseError)

    def test_exception_hierarchy_integrity(self) -> None:
        """Test that all exceptions maintain proper inheritance hierarchy."""

        # All specific exceptions inherit from base error
        assert issubclass(FlextMeltanoError, FlextMeltanoBaseError)
        assert issubclass(FlextMeltanoValidationError, FlextMeltanoBaseError)
        assert issubclass(FlextMeltanoConfigurationError, FlextMeltanoBaseError)
        assert issubclass(FlextMeltanoConnectionError, FlextMeltanoBaseError)
        assert issubclass(FlextMeltanoAuthenticationError, FlextMeltanoBaseError)
        assert issubclass(FlextMeltanoProcessingError, FlextMeltanoBaseError)
        assert issubclass(FlextMeltanoTimeoutError, FlextMeltanoBaseError)

    def test_exception_creation_with_args(self) -> None:
        """Test exception creation with various argument patterns."""

        # Single message
        error1 = FlextMeltanoError("Simple message")
        assert "Simple message" in str(error1)

        # Formatted message
        error2 = FlextMeltanoValidationError("Field: name, Value: invalid")
        assert "Field: name, Value: invalid" in str(error2)

    def test_exception_raising_and_catching(self) -> None:
        """Test raising and catching exceptions in realistic scenarios."""

        # Test specific exception catching
        validation_msg = "Validation failed"
        with pytest.raises(FlextMeltanoValidationError):
            raise FlextMeltanoValidationError(validation_msg)

        # Test base exception catching
        config_msg = "Config error"
        with pytest.raises(FlextMeltanoBaseError):
            raise FlextMeltanoConfigurationError(config_msg)

        # Test Exception base catching
        timeout_msg = "Timeout"
        with pytest.raises(Exception):
            raise FlextMeltanoTimeoutError(timeout_msg)

    def test_all_exceptions_are_available(self) -> None:
        """Test that all expected exceptions are available and properly defined."""

        exceptions = [
            FlextMeltanoBaseError,
            FlextMeltanoError,
            FlextMeltanoValidationError,
            FlextMeltanoConfigurationError,
            FlextMeltanoConnectionError,
            FlextMeltanoAuthenticationError,
            FlextMeltanoProcessingError,
            FlextMeltanoTimeoutError,
        ]

        for exception_class in exceptions:
            # Test class is properly defined as exception
            assert issubclass(exception_class, Exception)

            # Test instantiation works
            instance = exception_class("test message")
            assert "test message" in str(instance)


class TestExceptionUsagePatterns:
    """Test realistic exception usage patterns in FlextMeltano operations."""

    def test_meltano_project_validation_errors(self) -> None:
        """Test exception patterns for Meltano project validation."""

        def validate_meltano_project(project_path: str) -> None:
            if not project_path:
                msg = "Project path cannot be empty"
                raise FlextMeltanoValidationError(msg)
            if project_path == "/invalid":
                msg = "Invalid project configuration"
                raise FlextMeltanoConfigurationError(msg)

        # Test validation error
        with pytest.raises(
            FlextMeltanoValidationError, match="Project path cannot be empty"
        ):
            validate_meltano_project("")

        # Test configuration error
        with pytest.raises(
            FlextMeltanoConfigurationError, match="Invalid project configuration"
        ):
            validate_meltano_project("/invalid")

    def test_singer_tap_connection_errors(self) -> None:
        """Test exception patterns for Singer tap connections."""

        def connect_to_tap(tap_name: str, credentials: dict[str, str]) -> None:
            if not credentials.get("api_key"):
                msg = "API key required for tap connection"
                raise FlextMeltanoAuthenticationError(msg)
            if tap_name == "unreachable-tap":
                msg = "Cannot connect to tap service"
                raise FlextMeltanoConnectionError(msg)

        # Test authentication error
        with pytest.raises(FlextMeltanoAuthenticationError, match="API key required"):
            connect_to_tap("tap-github", {})

        # Test connection error
        with pytest.raises(
            FlextMeltanoConnectionError, match="Cannot connect to tap service"
        ):
            connect_to_tap("unreachable-tap", {"api_key": "valid"})

    def test_data_processing_timeout_errors(self) -> None:
        """Test exception patterns for data processing timeouts."""

        def process_large_dataset(timeout_seconds: int) -> None:
            if timeout_seconds <= 0:
                msg = "Processing timeout must be positive"
                raise FlextMeltanoTimeoutError(msg)
            if timeout_seconds < 60:
                msg = "Insufficient time for large dataset processing"
                raise FlextMeltanoProcessingError(msg)

        # Test timeout error
        with pytest.raises(
            FlextMeltanoTimeoutError, match="Processing timeout must be positive"
        ):
            process_large_dataset(0)

        # Test processing error
        with pytest.raises(FlextMeltanoProcessingError, match="Insufficient time"):
            process_large_dataset(30)
