"""FLEXT-Meltano Documentation Templates.

Template-based generation for CI/CD workflows, Makefiles, and Git hooks
using FLEXT architectural patterns.
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import cast

from flext_core import FlextLogger, FlextResult, FlextTypes


class DocsTemplates:
    """Template-based content generation for documentation automation."""

    def __init__(self, logger: FlextLogger | None = None) -> None:
        """Initialize templates with optional logger."""
        self._logger = logger

    def generate_ci_workflow(self, config: FlextTypes.Dict) -> FlextResult[str]:
        """Generate GitHub Actions workflow using template pattern.

        Args:
            config: Automation configuration dictionary

        Returns:
            FlextResult containing generated workflow YAML

        """
        try:
            automation = cast("FlextTypes.Dict", config.get("automation", {}))
            template_vars = {
                "generated_at": datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%S"),
                "audit_day": cast("str", automation.get("audit_day", "monday")),
                "audit_time": cast("str", automation.get("audit_time", "09:00")),
                "cron_schedule": self._get_cron_schedule(config),
            }

            workflow_content = self._ci_workflow_template.format(**template_vars)

            if self._logger:
                self._logger.info("CI workflow template generated", vars=template_vars)

            return FlextResult.ok(workflow_content)

        except Exception as e:
            error_msg = f"Failed to generate CI workflow: {e}"
            if self._logger:
                self._logger.exception("CI workflow generation failed", error=error_msg)
            return FlextResult.fail(error_msg)

    def generate_makefile_targets(self) -> FlextResult[str]:
        """Generate Makefile targets using template pattern.

        Returns:
            FlextResult containing generated Makefile content

        """
        try:
            makefile_content = self._makefile_targets_template

            if self._logger:
                self._logger.info("Makefile targets template generated")

            return FlextResult.ok(makefile_content)

        except Exception as e:
            error_msg = f"Failed to generate Makefile targets: {e}"
            if self._logger:
                self._logger.exception("Makefile generation failed", error=error_msg)
            return FlextResult.fail(error_msg)

    def generate_git_hook(self) -> FlextResult[str]:
        """Generate Git pre-commit hook using template pattern.

        Returns:
            FlextResult containing generated hook script

        """
        try:
            hook_content = self._git_hook_template

            if self._logger:
                self._logger.info("Git hook template generated")

            return FlextResult.ok(hook_content)

        except Exception as e:
            error_msg = f"Failed to generate Git hook: {e}"
            if self._logger:
                self._logger.exception("Git hook generation failed", error=error_msg)
            return FlextResult.fail(error_msg)

    def _get_cron_schedule(self, config: FlextTypes.Dict) -> str:
        """Convert audit schedule to cron format."""
        automation_config = cast("FlextTypes.Dict", config.get("automation", {}))
        audit_day = cast("str", automation_config.get("audit_day", "monday")).lower()
        audit_time = cast("str", automation_config.get("audit_time", "09:00"))

        hour, minute = map(int, audit_time.split(":"))

        # Day mapping for cron (0=Sunday, 1=Monday, etc.)
        day_map = {
            "sunday": 0,
            "monday": 1,
            "tuesday": 2,
            "wednesday": 3,
            "thursday": 4,
            "friday": 5,
            "saturday": 6,
        }

        day_num = day_map.get(audit_day, 1)  # Default to Monday

        return f"{minute} {hour} * * {day_num}"

    _ci_workflow_template = """# Documentation Quality CI/CD Pipeline
# Generated by FLEXT-Meltano Documentation Maintenance Framework
# Generated: {generated_at}

name: Documentation Quality

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'docs/**'
      - '**.md'
      - 'scripts/docs_maintenance.py'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'docs/**'
      - '**.md'
      - 'scripts/docs_maintenance.py'
  schedule:
    # Run weekly audit on {audit_day} at {audit_time} UTC
    - cron: '{cron_schedule}'

jobs:
  docs-quality-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyYAML requests

    - name: Run documentation quality audit
      run: python scripts/docs_maintenance.py --comprehensive

    - name: Check quality thresholds
      run: python scripts/docs_automation.py --ci-check

    - name: Upload quality reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: docs-quality-reports
        path: docs/reports/

    - name: Comment PR with quality report
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = require('path');

          // Read the quality summary
          const summaryPath = path.join(process.cwd(), 'docs/reports/docs_quality_summary.json');
          if (fs.existsSync(summaryPath)) {{
            const summary = JSON.parse(fs.readFileSync(summaryPath, 'utf8'));

            const qualityScore = summary.quality_score;
            const totalIssues = summary.issues.total;

            const body = `
            ## 📊 Documentation Quality Report

            **Quality Score:** ${{qualityScore}}/100
            **Total Issues:** ${{totalIssues}}

            ### Details
            - Files: ${{summary.metrics.total_files}}
            - Words: ${{summary.metrics.total_words.toLocaleString()}}
            - Links: ${{summary.metrics.total_links}}

            [View detailed report](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}})
            `;

            github.rest.issues.createComment({{
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            }});
          }}
"""

    _makefile_targets_template = """
# Documentation Maintenance Targets
# Generated by FLEXT-Meltano Documentation Maintenance Framework

.PHONY: docs-audit docs-validate docs-report docs-comprehensive docs-ci-check docs-schedule docs-hooks

# Run documentation quality audit
docs-audit:
	@echo "🔍 Running documentation audit..."
	@python scripts/docs_maintenance.py --audit

# Validate external links
docs-validate:
	@echo "🔗 Validating external links..."
	@python scripts/docs_maintenance.py --validate

# Generate quality reports
docs-report:
	@echo "📊 Generating quality reports..."
	@python scripts/docs_maintenance.py --report

# Run comprehensive documentation maintenance
docs-comprehensive:
	@echo "🔄 Running comprehensive documentation maintenance..."
	@python scripts/docs_maintenance.py --comprehensive

# Run CI quality checks
docs-ci-check:
	@echo "🔍 Running CI documentation quality checks..."
	@python scripts/docs_automation.py --ci-check

# Start scheduled maintenance monitoring
docs-schedule:
	@echo "📅 Starting scheduled documentation maintenance..."
	@python scripts/docs_automation.py --schedule

# Set up Git hooks for quality checks
docs-hooks:
	@echo "🔧 Setting up Git hooks for documentation quality..."
	@python scripts/docs_automation.py --setup-hooks

# Generate GitHub Actions workflow
docs-workflow:
	@echo "⚙️  Generating GitHub Actions workflow..."
	@python scripts/docs_automation.py --generate-workflow > .github/workflows/docs-quality.yml
	@echo "✅ Workflow generated: .github/workflows/docs-quality.yml"

# View latest quality report
docs-view-report:
	@echo "📊 Latest Documentation Quality Report"
	@echo "======================================"
	@if [ -f "docs/reports/docs_quality_summary.json" ]; then \\
		python -c "\\
import json\\
with open('docs/reports/docs_quality_summary.json', 'r') as f:\\
    data = json.load(f)\\
    print(f'Quality Score: {data[\"quality_score\"]}/100')\\
    print(f'Total Issues: {data[\"issues\"][\"total\"]}')\\
    print(f'Files: {data[\"metrics\"][\"total_files\"]}')\\
    print(f'Words: {data[\"metrics\"][\"total_words\"]:,}')\\
    print(f'Links: {data[\"metrics\"][\"total_links\"]}')\\
"; \\
	else \\
		echo "No quality report found. Run 'make docs-comprehensive' first."; \\
	fi

# Clean up generated reports
docs-clean:
	@echo "🧹 Cleaning up documentation reports..."
	@rm -rf docs/reports/*
	@echo "✅ Reports cleaned"

# Full documentation maintenance setup
docs-setup: docs-hooks docs-workflow
	@echo "🚀 Documentation maintenance system setup complete!"
	@echo ""
	@echo "Next steps:"
	@echo "1. Run 'make docs-comprehensive' to generate initial quality report"
	@echo "2. Review quality report in docs/reports/"
	@echo "3. Address high-priority issues"
	@echo "4. Commit changes to enable pre-commit hooks"
"""

    _git_hook_template = """#!/bin/bash
# FLEXT-Meltano Documentation Quality Pre-commit Hook
# Generated by Documentation Maintenance Framework

echo "🔍 Running documentation quality checks..."

# Run documentation audit
python scripts/docs_maintenance.py --audit

# Check if audit passed
if [ $? -ne 0 ]; then
    echo "❌ Documentation quality check failed. Please fix issues before committing."
    echo "Run 'python scripts/docs_maintenance.py --comprehensive' for detailed report."
    exit 1
fi

# Check for critical issues
if [ -f "docs/reports/docs_quality_summary.json" ]; then
    CRITICAL_ISSUES=$(python -c "
import json
with open('docs/reports/docs_quality_summary.json', 'r') as f:
    data = json.load(f)
    print(data.get('issues', {}).get('by_severity', {}).get('critical', 0))
")

    if [ "$CRITICAL_ISSUES" -gt 0 ]; then
        echo "❌ Critical documentation issues found: $CRITICAL_ISSUES"
        echo "Please fix critical issues before committing."
        exit 1
    fi
fi

echo "✅ Documentation quality checks passed"
exit 0
"""
