# AUTO-GENERATED FILE — DO NOT EDIT MANUALLY.
# Regenerate with: make gen
#
"""Flext meltano package."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import TYPE_CHECKING as _TYPE_CHECKING

from flext_core.lazy import install_lazy_exports, merge_lazy_imports
from flext_meltano.__version__ import (
    __all__,
    __author__,
    __author_email__,
    __description__,
    __license__,
    __title__,
    __url__,
    __version__,
    __version_info__,
)

if _TYPE_CHECKING:
    from flext_core import FlextTypes
    from flext_core.decorators import FlextDecorators as d
    from flext_core.exceptions import FlextExceptions as e
    from flext_core.handlers import FlextHandlers as h
    from flext_core.mixins import FlextMixins as x
    from flext_core.result import FlextResult as r
    from flext_core.service import FlextService as s
    from flext_meltano import (
        _constants,
        _models,
        _protocols,
        _typings,
        _utilities,
        abstractions,
        adapter_extensions,
        adapters,
        api,
        base,
        bridge,
        cli,
        cli_managers,
        cli_params,
        config,
        constants,
        consumer_bases,
        context,
        core,
        dbt_project,
        dbt_runner,
        dbt_service_base,
        discovery,
        domains,
        enums,
        executor,
        file_managers,
        instances,
        instances_data,
        library_runner,
        logging_config,
        meltano_dbt_transformation,
        meltano_plugin_discovery,
        meltano_plugins,
        meltano_project_sdk,
        models,
        payloads,
        payloads_data,
        plugin,
        project,
        project_service,
        projects,
        projects_plugin,
        protocols,
        results,
        results_dbt,
        results_pipeline,
        runtime,
        sdk,
        services,
        settings,
        singer,
        singer_catalog,
        singer_sdk,
        singer_state,
        singer_tap,
        singer_target,
        singer_translator,
        sources,
        sources_params,
        tap_service_base,
        target_service_base,
        transformations,
        typings,
        utilities,
        validators,
        yaml,
    )
    from flext_meltano._constants import (
        FlextMeltanoConstantsBase,
        FlextMeltanoConstantsConfig,
        FlextMeltanoConstantsEnums,
    )
    from flext_meltano._models import (
        FlextMeltanoModelsCliParams,
        FlextMeltanoModelsContext,
        FlextMeltanoModelsCore,
        FlextMeltanoModelsDiscovery,
        FlextMeltanoModelsInstances,
        FlextMeltanoModelsInstancesData,
        FlextMeltanoModelsLogging,
        FlextMeltanoModelsPayloads,
        FlextMeltanoModelsPayloadsData,
        FlextMeltanoModelsProjects,
        FlextMeltanoModelsProjectsPlugin,
        FlextMeltanoModelsResults,
        FlextMeltanoModelsResultsDbt,
        FlextMeltanoModelsResultsPipeline,
        FlextMeltanoModelsSinger,
        FlextMeltanoModelsSingerCatalog,
        FlextMeltanoModelsSingerSdk,
        FlextMeltanoModelsSources,
        FlextMeltanoModelsSourcesParams,
        FlextMeltanoModelsTransformations,
    )
    from flext_meltano._protocols import (
        FlextMeltanoProtocolsBase,
        FlextMeltanoProtocolsPlugin,
        FlextMeltanoProtocolsProject,
        FlextMeltanoProtocolsServices,
        FlextMeltanoProtocolsSinger,
    )
    from flext_meltano._typings import (
        FlextMeltanoTypingsBase,
        FlextMeltanoTypingsDomains,
        FlextMeltanoTypingsSinger,
    )
    from flext_meltano._utilities import (
        FlextMeltanoUtilitiesConfig,
        FlextMeltanoUtilitiesProject,
        FlextMeltanoUtilitiesRuntime,
        FlextMeltanoUtilitiesSinger,
        FlextMeltanoUtilitiesYaml,
        SingerTargetHandler,
    )
    from flext_meltano.api import FlextMeltano, meltano
    from flext_meltano.base import FlextMeltanoServiceBase
    from flext_meltano.cli import main
    from flext_meltano.constants import (
        FlextMeltanoConstants,
        FlextMeltanoConstants as c,
    )
    from flext_meltano.models import FlextMeltanoModels, FlextMeltanoModels as m
    from flext_meltano.protocols import (
        FlextMeltanoProtocols,
        FlextMeltanoProtocols as p,
    )
    from flext_meltano.services import (
        OPERATION_ERRORS,
        FlextMeltanoAbstractions,
        FlextMeltanoAbstractionsBase,
        FlextMeltanoAdapter,
        FlextMeltanoBridge,
        FlextMeltanoCLI,
        FlextMeltanoCommandRouter,
        FlextMeltanoComponentService,
        FlextMeltanoDbtAdapter,
        FlextMeltanoDbtProjectMixin,
        FlextMeltanoDbtRunnerMixin,
        FlextMeltanoDbtTransformationRunner,
        FlextMeltanoExecutor,
        FlextMeltanoExecutorBase,
        FlextMeltanoFileManagers,
        FlextMeltanoLibraryRunner,
        FlextMeltanoPipelineAdapter,
        FlextMeltanoPipelineLifecycleOperations,
        FlextMeltanoPipelineManager,
        FlextMeltanoPipelinePaths,
        FlextMeltanoPluginDiscoveryMixin,
        FlextMeltanoProjectManager,
        FlextMeltanoProjectService,
        FlextMeltanoService,
        FlextMeltanoSingerCatalogMixin,
        FlextMeltanoSingerCliTranslator,
        FlextMeltanoSingerStateMixin,
        FlextMeltanoTapAbstractions,
        FlextMeltanoTapSourceMixin,
        FlextMeltanoTargetAbstractions,
        FlextMeltanoValidators,
    )
    from flext_meltano.services.consumer_bases import (
        FlextMeltanoDbtServiceBase,
        FlextMeltanoTapServiceBase,
        FlextMeltanoTargetServiceBase,
    )
    from flext_meltano.settings import FlextMeltanoSettings
    from flext_meltano.singer import (
        FlextMeltanoSingerContext,
        FlextMeltanoSingerRecord,
        FlextMeltanoSingerSinkBase,
        FlextMeltanoSingerStreamBase,
        FlextMeltanoSingerTapBase,
        FlextMeltanoSingerTargetBase,
    )
    from flext_meltano.typings import FlextMeltanoTypes, FlextMeltanoTypes as t
    from flext_meltano.utilities import (
        FlextMeltanoUtilities,
        FlextMeltanoUtilities as u,
    )

_LAZY_IMPORTS: FlextTypes.LazyImportIndex = merge_lazy_imports(
    (
        "flext_meltano._constants",
        "flext_meltano._models",
        "flext_meltano._protocols",
        "flext_meltano._typings",
        "flext_meltano._utilities",
        "flext_meltano.services",
        "flext_meltano.singer",
    ),
    {
        "FlextMeltano": "flext_meltano.api",
        "FlextMeltanoConstants": "flext_meltano.constants",
        "FlextMeltanoModels": "flext_meltano.models",
        "FlextMeltanoProtocols": "flext_meltano.protocols",
        "FlextMeltanoServiceBase": "flext_meltano.base",
        "FlextMeltanoSettings": "flext_meltano.settings",
        "FlextMeltanoTypes": "flext_meltano.typings",
        "FlextMeltanoUtilities": "flext_meltano.utilities",
        "_constants": "flext_meltano._constants",
        "_models": "flext_meltano._models",
        "_protocols": "flext_meltano._protocols",
        "_typings": "flext_meltano._typings",
        "_utilities": "flext_meltano._utilities",
        "abstractions": "flext_meltano.abstractions",
        "adapter_extensions": "flext_meltano.adapter_extensions",
        "adapters": "flext_meltano.adapters",
        "api": "flext_meltano.api",
        "base": "flext_meltano.base",
        "bridge": "flext_meltano.bridge",
        "c": ("flext_meltano.constants", "FlextMeltanoConstants"),
        "cli": "flext_meltano.cli",
        "cli_managers": "flext_meltano.cli_managers",
        "cli_params": "flext_meltano.cli_params",
        "config": "flext_meltano.config",
        "constants": "flext_meltano.constants",
        "consumer_bases": "flext_meltano.consumer_bases",
        "context": "flext_meltano.context",
        "core": "flext_meltano.core",
        "d": ("flext_core.decorators", "FlextDecorators"),
        "dbt_project": "flext_meltano.dbt_project",
        "dbt_runner": "flext_meltano.dbt_runner",
        "dbt_service_base": "flext_meltano.dbt_service_base",
        "discovery": "flext_meltano.discovery",
        "domains": "flext_meltano.domains",
        "e": ("flext_core.exceptions", "FlextExceptions"),
        "enums": "flext_meltano.enums",
        "executor": "flext_meltano.executor",
        "file_managers": "flext_meltano.file_managers",
        "h": ("flext_core.handlers", "FlextHandlers"),
        "instances": "flext_meltano.instances",
        "instances_data": "flext_meltano.instances_data",
        "library_runner": "flext_meltano.library_runner",
        "logging_config": "flext_meltano.logging_config",
        "m": ("flext_meltano.models", "FlextMeltanoModels"),
        "main": "flext_meltano.cli",
        "meltano": "flext_meltano.api",
        "meltano_dbt_transformation": "flext_meltano.meltano_dbt_transformation",
        "meltano_plugin_discovery": "flext_meltano.meltano_plugin_discovery",
        "meltano_plugins": "flext_meltano.meltano_plugins",
        "meltano_project_sdk": "flext_meltano.meltano_project_sdk",
        "models": "flext_meltano.models",
        "p": ("flext_meltano.protocols", "FlextMeltanoProtocols"),
        "payloads": "flext_meltano.payloads",
        "payloads_data": "flext_meltano.payloads_data",
        "plugin": "flext_meltano.plugin",
        "project": "flext_meltano.project",
        "project_service": "flext_meltano.project_service",
        "projects": "flext_meltano.projects",
        "projects_plugin": "flext_meltano.projects_plugin",
        "protocols": "flext_meltano.protocols",
        "r": ("flext_core.result", "FlextResult"),
        "results": "flext_meltano.results",
        "results_dbt": "flext_meltano.results_dbt",
        "results_pipeline": "flext_meltano.results_pipeline",
        "runtime": "flext_meltano.runtime",
        "s": ("flext_core.service", "FlextService"),
        "sdk": "flext_meltano.sdk",
        "services": "flext_meltano.services",
        "settings": "flext_meltano.settings",
        "singer": "flext_meltano.singer",
        "singer_catalog": "flext_meltano.singer_catalog",
        "singer_sdk": "flext_meltano.singer_sdk",
        "singer_state": "flext_meltano.singer_state",
        "singer_tap": "flext_meltano.singer_tap",
        "singer_target": "flext_meltano.singer_target",
        "singer_translator": "flext_meltano.singer_translator",
        "sources": "flext_meltano.sources",
        "sources_params": "flext_meltano.sources_params",
        "t": ("flext_meltano.typings", "FlextMeltanoTypes"),
        "tap_service_base": "flext_meltano.tap_service_base",
        "target_service_base": "flext_meltano.target_service_base",
        "transformations": "flext_meltano.transformations",
        "typings": "flext_meltano.typings",
        "u": ("flext_meltano.utilities", "FlextMeltanoUtilities"),
        "utilities": "flext_meltano.utilities",
        "validators": "flext_meltano.validators",
        "x": ("flext_core.mixins", "FlextMixins"),
        "yaml": "flext_meltano.yaml",
    },
)


install_lazy_exports(
    __name__,
    globals(),
    _LAZY_IMPORTS,
    [
        "__all__",
        "__author__",
        "__author_email__",
        "__description__",
        "__license__",
        "__title__",
        "__url__",
        "__version__",
        "__version_info__",
    ],
)
