"""FLEXT Meltano Exceptions - Generated exception classes.

Uses flext-core create_module_exception_classes - NO local implementations.
All exceptions are generated by flext-core SOURCE OF TRUTH.

Copyright (c) 2025 FLEXT Team. All rights reserved.
SPDX-License-Identifier: MIT
"""

from flext_core import FlextExceptions

# ============================================================================
# DIRECT FLEXT-CORE USAGE - Generated exceptions only, no duplications
# ============================================================================

# Generate ALL module exceptions using flext-core SOURCE OF TRUTH
_exceptions = FlextExceptions.create_module_exception_classes("flext_meltano")

# Use generated exceptions directly - NO additional aliases or wrappers
FlextMeltanoBaseError = _exceptions["FLEXT_MELTANOBaseError"]
FlextMeltanoError = _exceptions["FLEXT_MELTANOError"]
FlextMeltanoConfigurationError = _exceptions["FLEXT_MELTANOConfigurationError"]
FlextMeltanoConnectionError = _exceptions["FLEXT_MELTANOConnectionError"]
FlextMeltanoValidationError = _exceptions["FLEXT_MELTANOValidationError"]
FlextMeltanoAuthenticationError = _exceptions["FLEXT_MELTANOAuthenticationError"]
FlextMeltanoProcessingError = _exceptions["FLEXT_MELTANOProcessingError"]
FlextMeltanoTimeoutError = _exceptions["FLEXT_MELTANOTimeoutError"]

# ============================================================================
# EXPORTS - Only the essentials, no wrappers
# ============================================================================

__all__ = [
    "FlextMeltanoAuthenticationError",
    "FlextMeltanoBaseError",
    "FlextMeltanoConfigurationError",
    "FlextMeltanoConnectionError",
    "FlextMeltanoError",
    "FlextMeltanoProcessingError",
    "FlextMeltanoTimeoutError",
    "FlextMeltanoValidationError",
]
