"""Constants for tests.unit._constants."""

from __future__ import annotations

TEST_EXECUTION_TIME_SUCCESS: float = 1.5

TEST_EXECUTION_TIME_FAILURE: float = 0.5

TEST_EXECUTION_TIME_DICT_SUCCESS: float = 0.2

TEST_EXECUTION_TIME_DICT_FAILURE: float = 0.1

TEST_EXECUTION_TIME_JSON_SUCCESS: float = 2.0

TEST_EXECUTION_TIME_JSON_FAILURE: float = 0.3

TEST_EXECUTION_TIME_JSON_ERROR: float = 5.5

TEST_EXECUTION_TIME_HOUR: float = 3600.5

TEST_COMMAND_COUNT: int = 2
