"""Test module for flext-meltano."""

from __future__ import annotations

import pytest
from flext_core import FlextTypes

from flext_meltano import FlextMeltanoExceptions


class TestFlextMeltanoExceptions:
    """Test flext-core generated FlextMeltano exceptions - ZERO duplication."""

    def test_base_error_functionality(self) -> None:
        """Test FlextMeltanoExceptions.BaseError - generated by flext-core."""
        error = FlextMeltanoExceptions.BaseError("Base error message")
        assert "Base error message" in str(error)
        assert isinstance(error, Exception)

    def test_meltano_error_functionality(self) -> None:
        """Test FlextMeltanoExceptions.Error - generated by flext-core."""
        error = FlextMeltanoExceptions.Error("Meltano operation failed")
        assert "Meltano operation failed" in str(error)
        assert isinstance(error, FlextMeltanoExceptions.BaseError)

    def test_validation_error_functionality(self) -> None:
        """Test FlextMeltanoExceptions.ValidationError - generated by flext-core."""
        error = FlextMeltanoExceptions.ValidationError(
            "Validation failed for field 'name'"
        )
        assert "Validation failed for field 'name'" in str(error)
        assert isinstance(error, FlextMeltanoExceptions.BaseError)

    def test_configuration_error_functionality(self) -> None:
        """Test FlextMeltanoExceptions.ConfigurationError - generated by flext-core."""
        error = FlextMeltanoExceptions.ConfigurationError("Invalid configuration")
        assert "Invalid configuration" in str(error)
        assert isinstance(error, FlextMeltanoExceptions.BaseError)

    def test_connection_error_functionality(self) -> None:
        """Test FlextMeltanoExceptions.ConnectionError - generated by flext-core."""
        error = FlextMeltanoExceptions.ConnectionError("Database connection failed")
        assert "Database connection failed" in str(error)
        assert isinstance(error, FlextMeltanoExceptions.BaseError)

    def test_authentication_error_functionality(self) -> None:
        """Test FlextMeltanoExceptions.AuthenticationError - generated by flext-core."""
        error = FlextMeltanoExceptions.AuthenticationError("Authentication failed")
        assert "Authentication failed" in str(error)
        assert isinstance(error, FlextMeltanoExceptions.BaseError)

    def test_processing_error_functionality(self) -> None:
        """Test FlextMeltanoExceptions.ProcessingError - generated by flext-core."""
        error = FlextMeltanoExceptions.ProcessingError("Data processing failed")
        assert "Data processing failed" in str(error)
        assert isinstance(error, FlextMeltanoExceptions.BaseError)

    def test_timeout_error_functionality(self) -> None:
        """Test FlextMeltanoExceptions.TimeoutError - generated by flext-core."""
        error = FlextMeltanoExceptions.TimeoutError("Operation timed out")
        assert "Operation timed out" in str(error)
        assert isinstance(error, FlextMeltanoExceptions.BaseError)

    def test_exception_hierarchy_integrity(self) -> None:
        """Test that all exceptions maintain proper inheritance hierarchy."""
        # All specific exceptions inherit from base error
        assert issubclass(
            FlextMeltanoExceptions.Error, FlextMeltanoExceptions.BaseError
        )
        assert issubclass(
            FlextMeltanoExceptions.ValidationError, FlextMeltanoExceptions.BaseError
        )
        assert issubclass(
            FlextMeltanoExceptions.ConfigurationError, FlextMeltanoExceptions.BaseError
        )
        assert issubclass(
            FlextMeltanoExceptions.ConnectionError, FlextMeltanoExceptions.BaseError
        )
        assert issubclass(
            FlextMeltanoExceptions.AuthenticationError, FlextMeltanoExceptions.BaseError
        )
        assert issubclass(
            FlextMeltanoExceptions.ProcessingError, FlextMeltanoExceptions.BaseError
        )
        assert issubclass(
            FlextMeltanoExceptions.TimeoutError, FlextMeltanoExceptions.BaseError
        )

    def test_exception_creation_with_args(self) -> None:
        """Test exception creation with various argument patterns."""
        # Single message
        error1 = FlextMeltanoExceptions.Error("Simple message")
        assert "Simple message" in str(error1)

        # Formatted message
        error2 = FlextMeltanoExceptions.ValidationError("Field: name, Value: invalid")
        assert "Field: name, Value: invalid" in str(error2)

    def test_exception_raising_and_catching(self) -> None:
        """Test raising and catching exceptions in realistic scenarios."""
        # Test specific exception catching
        validation_msg = "Validation failed"
        with pytest.raises(FlextMeltanoExceptions.ValidationError):
            raise FlextMeltanoExceptions.ValidationError(validation_msg)

        # Test base exception catching
        config_msg = "Config error"
        with pytest.raises(FlextMeltanoExceptions.BaseError):
            raise FlextMeltanoExceptions.ConfigurationError(config_msg)

        # Test Exception base catching
        timeout_msg = "Timeout"
        with pytest.raises(Exception):
            raise FlextMeltanoExceptions.TimeoutError(timeout_msg)

    def test_all_exceptions_are_available(self) -> None:
        """Test that all expected exceptions are available and properly defined."""
        exceptions = [
            FlextMeltanoExceptions.BaseError,
            FlextMeltanoExceptions.Error,
            FlextMeltanoExceptions.ValidationError,
            FlextMeltanoExceptions.ConfigurationError,
            FlextMeltanoExceptions.ConnectionError,
            FlextMeltanoExceptions.AuthenticationError,
            FlextMeltanoExceptions.ProcessingError,
            FlextMeltanoExceptions.TimeoutError,
        ]

        for exception_class in exceptions:
            # Test class is properly defined as exception
            assert issubclass(exception_class, Exception)

            # Test instantiation works
            instance = exception_class("test message")
            assert "test message" in str(instance)


class TestExceptionUsagePatterns:
    """Test realistic exception usage patterns in FlextMeltano operations."""

    def test_meltano_project_validation_errors(self) -> None:
        """Test exception patterns for Meltano project validation."""

        def validate_meltano_project(project_path: str) -> None:
            if not project_path:
                msg = "Project path cannot be empty"
                raise FlextMeltanoExceptions.ValidationError(msg)
            if project_path == "/invalid":
                msg = "Invalid project configuration"
                raise FlextMeltanoExceptions.ConfigurationError(msg)

        # Test validation error
        with pytest.raises(
            FlextMeltanoExceptions.ValidationError,
            match="Project path cannot be empty",
        ):
            validate_meltano_project("")

        # Test configuration error
        with pytest.raises(
            FlextMeltanoExceptions.ConfigurationError,
            match="Invalid project configuration",
        ):
            validate_meltano_project("/invalid")

    def test_singer_tap_connection_errors(self) -> None:
        """Test exception patterns for Singer tap connections."""

        def connect_to_tap(tap_name: str, credentials: FlextTypes.StringDict) -> None:
            if not credentials.get("api_key"):
                msg = "API key required for tap connection"
                raise FlextMeltanoExceptions.AuthenticationError(msg)
            if tap_name == "unreachable-tap":
                msg = "Cannot connect to tap service"
                raise FlextMeltanoExceptions.ConnectionError(msg)

        # Test authentication error
        with pytest.raises(
            FlextMeltanoExceptions.AuthenticationError, match="API key required"
        ):
            connect_to_tap("tap-github", {})

        # Test connection error
        with pytest.raises(
            FlextMeltanoExceptions.ConnectionError,
            match="Cannot connect to tap service",
        ):
            connect_to_tap("unreachable-tap", {"api_key": "valid"})

    def test_data_processing_timeout_errors(self) -> None:
        """Test exception patterns for data processing timeouts."""

        def process_large_dataset(timeout_seconds: int) -> None:
            if timeout_seconds <= 0:
                msg = "Processing timeout must be positive"
                raise FlextMeltanoExceptions.TimeoutError(msg)
            if timeout_seconds < 60:
                msg = "Insufficient time for large dataset processing"
                raise FlextMeltanoExceptions.ProcessingError(msg)

        # Test timeout error
        with pytest.raises(
            FlextMeltanoExceptions.TimeoutError,
            match="Processing timeout must be positive",
        ):
            process_large_dataset(0)

        # Test processing error
        with pytest.raises(
            FlextMeltanoExceptions.ProcessingError, match="Insufficient time"
        ):
            process_large_dataset(30)
